// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soundia.Api.Data;

#nullable disable

namespace Soundia.Api.Migrations
{
    [DbContext(typeof(SoundiaDbContext))]
    [Migration("20260306092155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Soundia.Api.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Soundia.Api.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Soundia.Api.Models.PlaylistSong", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaylistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("Soundia.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "NeonWave",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            CoverUrl = "https://picsum.photos/seed/song1/300/300",
                            Duration = "3:42",
                            Title = "Midnight Pulse"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "SynthCity",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
                            CoverUrl = "https://picsum.photos/seed/song2/300/300",
                            Duration = "4:15",
                            Title = "Electric Dreams"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Digital Aura",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
                            CoverUrl = "https://picsum.photos/seed/song3/300/300",
                            Duration = "3:58",
                            Title = "Cyber Horizon"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Futura",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
                            CoverUrl = "https://picsum.photos/seed/song4/300/300",
                            Duration = "4:32",
                            Title = "Neon Lights"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Cosmos",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
                            CoverUrl = "https://picsum.photos/seed/song5/300/300",
                            Duration = "3:21",
                            Title = "Starfall"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Velocity",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
                            CoverUrl = "https://picsum.photos/seed/song6/300/300",
                            Duration = "5:07",
                            Title = "Retrograde"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "CodeBreaker",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
                            CoverUrl = "https://picsum.photos/seed/song7/300/300",
                            Duration = "4:44",
                            Title = "Binary Sunset"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Particle",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
                            CoverUrl = "https://picsum.photos/seed/song8/300/300",
                            Duration = "3:33",
                            Title = "Quantum Beat"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "DarkMatter",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
                            CoverUrl = "https://picsum.photos/seed/song9/300/300",
                            Duration = "4:19",
                            Title = "Void Walker"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Skyline",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
                            CoverUrl = "https://picsum.photos/seed/song10/300/300",
                            Duration = "3:56",
                            Title = "Aurora"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "NeonWave",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            CoverUrl = "https://picsum.photos/seed/song1/300/300",
                            Duration = "3:42",
                            Title = "Midnight Pulse"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "SynthCity",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
                            CoverUrl = "https://picsum.photos/seed/song2/300/300",
                            Duration = "4:15",
                            Title = "Electric Dreams"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Digital Aura",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
                            CoverUrl = "https://picsum.photos/seed/song3/300/300",
                            Duration = "3:58",
                            Title = "Cyber Horizon"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Futura",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
                            CoverUrl = "https://picsum.photos/seed/song4/300/300",
                            Duration = "4:32",
                            Title = "Neon Lights"
                        },
                        new
                        {
                            Id = 15,
                            Artist = "Cosmos",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
                            CoverUrl = "https://picsum.photos/seed/song5/300/300",
                            Duration = "3:21",
                            Title = "Starfall"
                        },
                        new
                        {
                            Id = 16,
                            Artist = "Velocity",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
                            CoverUrl = "https://picsum.photos/seed/song6/300/300",
                            Duration = "5:07",
                            Title = "Retrograde"
                        },
                        new
                        {
                            Id = 17,
                            Artist = "CodeBreaker",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
                            CoverUrl = "https://picsum.photos/seed/song7/300/300",
                            Duration = "4:44",
                            Title = "Binary Sunset"
                        },
                        new
                        {
                            Id = 18,
                            Artist = "Particle",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
                            CoverUrl = "https://picsum.photos/seed/song8/300/300",
                            Duration = "3:33",
                            Title = "Quantum Beat"
                        },
                        new
                        {
                            Id = 19,
                            Artist = "DarkMatter",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
                            CoverUrl = "https://picsum.photos/seed/song9/300/300",
                            Duration = "4:19",
                            Title = "Void Walker"
                        },
                        new
                        {
                            Id = 20,
                            Artist = "Skyline",
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
                            CoverUrl = "https://picsum.photos/seed/song10/300/300",
                            Duration = "3:56",
                            Title = "Aurora"
                        },
                        new
                        {
                            Id = 21,
                            Artist = "Suno",
                            AudioUrl = "/audio/LƯỚT QUA TIM ANH.mp3",
                            CoverUrl = "https://picsum.photos/seed/song3/300/300",
                            Duration = "2:29",
                            Title = "Lướt Qua Tim Anh"
                        });
                });

            modelBuilder.Entity("Soundia.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Soundia.Api.Models.Favorite", b =>
                {
                    b.HasOne("Soundia.Api.Models.Song", "Song")
                        .WithMany("Favorites")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soundia.Api.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soundia.Api.Models.Playlist", b =>
                {
                    b.HasOne("Soundia.Api.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soundia.Api.Models.PlaylistSong", b =>
                {
                    b.HasOne("Soundia.Api.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soundia.Api.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Soundia.Api.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Soundia.Api.Models.Song", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Soundia.Api.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
